### ISSUE TITLE
Is there any plan to publish this as a library?

### ISSUE THREAD

**Issue by Bohooslav** [the-syndrome/meltdown#1]

**Comment by the-syndrome** [comment]
We went over some of it in chat. I'd like this project to remain as a template but roll the learning from this into another project that is a CLI and a library like next, nuxt, hexo, gatsby, and etc.

One of the benefits of the template is that nothing is a mysterious black box. The user can fully access all the code without learning a bunch of APIs. The down side is that each new site I make is challenging to update with diffs.

The benefits of having the CLI and library would be you could use it across many projects without duplicating as much. It would make projects easier to upgrade the core components. The trade off is less hackable unless people are comfortable editing `node_modules` or `patch-package`.
