### ISSUE TITLE
Test dev tasks e.g. `npm run dev`

### ISSUE THREAD

**Issue by the-syndrome** [the-syndrome/meltdown#2]
"I tried to run it locally, `npm run dev` didn't work, said it cannot connect to 127.0.0.1:port, but `npm start did work." From @Bohooslav in chat.

Originally this was only tested on linux. I don't have a Windows machine to test with right now.

+ [x] Re-test all dev tasks a.k.a. package.json scripts
+ [x] Add a good site scanner, 404 checker CLI
+ [ ] Try to find a Windows machine or CI
+ [x] Update if changed

**Comment by Bohooslav** [comment]
I have Fedora Linux btw
It builds the project, but when I go to localhost:3000 or http://127.0.0.1:33765 it gives the next error
```
✔ src/server.imba: listening on http://localhost:3000
node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

Error: connect ECONNREFUSED 127.0.0.1:33765
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 33765,
  response: undefined
}

Node.js v22.8.0
× src/server.imba: exited with error code: 1
```

**Comment by the-syndrome** [comment]
Thank you. There might be an issue where imba is not respecting our `.env` file `PORT`.

Maybe a work-around is `.env` `PORT=3000`.

And `package.json#scripts` `"dev-server": "PORT=3000 imba -w src/server.imba || true",` https://github.com/the-syndrome/meltdown/blob/master/package.json#L37C5-L37C53

I think right now there is some issue with imba where it only wants to run port 3000. It does not always respect our http server listen. https://github.com/the-syndrome/meltdown/blob/master/src/server.imba#L180

**Comment by Bohooslav** [comment]
Yeah, changing the port to 3000 works.

**Comment by the-syndrome** [comment]
I found an issue with the bundler, maybe imba+esbuild, where these two codes yield two different results:

```imba
# wrong port forced by imba
const { PORT: port } = process.env

# correct port from .env
const port = process.env.PORT 
```

In the next release hopefully this is working smoothly.

**Comment by the-syndrome** [comment]
A huge update just pushed. I'll make an announcement soon with some interesting info about it.
